/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Billboard.glb -o src/components/Billboard.js -k -K -r public 
*/


import { Html, useGLTF } from "@react-three/drei";
import { useAtom } from "jotai";
import { degToRad } from "three/src/math/MathUtils";
import { currentPageAtom } from "./UI";
import { useNavigate } from 'react-router-dom';
import './Billboard.css';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { useThree  } from "@react-three/fiber";
import { useEffect, useRef } from "react";
import { Raycaster, Vector2, Vector3 } from "three"; 

export const OverlayItem = ({
    className = "",
    title,
    description,
    price,
    bgColor,
    ...props
}) => {
    const [currentPage] = useAtom(currentPageAtom);
    const navigate = useNavigate();
    const openModel = useRef();
    const openLoader = new GLTFLoader();
    const { scene} = useThree();


  
    const handleEnterButtonClick = () => {
      // Navigate to the profile page when the model is clicked
      navigate('/Home');
    };
  
    
      openLoader.load('/models/Welcome.glb', (gltf) => {
        openModel.current = gltf.scene;
        openModel.current.scale.set(1, 1, 1); // Adjust the scale as needed
        openModel.current.position.set(-.05, -0.5, 4.1); // Adjust the position as needed
        openModel.current.rotation.y += 0.525;
        scene.add(openModel.current);
        
    
      });

    return (
        <Html
            transform
            distanceFactor={1}
            center
            className={`w-48 rounded-md overflow-hidden ${currentPage === "home" ? "" : "opacity-0"
                } transition-opacity duration-1000 ${className}`}
            {...props}
        >
            {openModel.current && (
              <primitive object={openModel.current} />
            )}
            <button
                onClick={handleEnterButtonClick}

                className=" custom-button"
            >
                OPEN TO DISCOVER
            </  button>
            

        </Html>
    );
};

export function Model(props) {
    const { nodes, materials } = useGLTF('./models/Billboard.glb')
    return (
        <group {...props} dispose={null}>
            <group>
                <group {...props} dispose={null}>
                    <group name="Billboard_2">
                        <group position={[1.122, 0.154, -0.288]}>
                            <mesh name="Billboard_2_1002" geometry={nodes.Billboard_2_1002.geometry} material={materials['lambert3SG.002']} />
                            {Html && (
                                <OverlayItem
                                    rotation-y={degToRad(20)}
                                    position-x={-.2}
                                    position-z={-2.2}
                                    position-y={0.9}
                                    title={"Open to Discover"}

                                    price={"129.99"}
                                    bgColor={"bg-yellow-500"}
                                    className={"transition delay-1000"}
                                />
                            )}
                            <mesh name="Billboard_2_1002" geometry={nodes.Billboard_2_1002.geometry} material={materials['lambert3SG.002']} />
                            <mesh name="Billboard_2_1002_1" geometry={nodes.Billboard_2_1002_1.geometry} material={materials['Material.006']} />
                            <mesh name="Billboard_2_1002_2" geometry={nodes.Billboard_2_1002_2.geometry} material={materials['Material.001']} />
                            <mesh name="Billboard_2_1002_3" geometry={nodes.Billboard_2_1002_3.geometry} material={materials['Material.002']} />
                            <mesh name="Billboard_2_1002_4" geometry={nodes.Billboard_2_1002_4.geometry} material={materials['Material.004']} />
                            <mesh name="Billboard_2_1002_5" geometry={nodes.Billboard_2_1002_5.geometry} material={materials['Material.005']} />
                            <mesh name="Billboard_2_1002_6" geometry={nodes.Billboard_2_1002_6.geometry} material={materials['Material.003']} />
                            <mesh name="Billboard_2_1002_7" geometry={nodes.Billboard_2_1002_7.geometry} material={materials['Material.007']} />
                        </group>
                    </group>
                </group>
            </group>
        </group>



    )
}
useGLTF.preload('/models/Billboard.glb')
