/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Projects.gltf -o src/components/ProjectsText.js -k -K -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import ProjectsModel from './assets/3d/Projects.glb';

export default function Model(props) {
  const { nodes, materials } = useGLTF(ProjectsModel)
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group name="Projects" rotation={[Math.PI / 2, 0, 0]} scale={2.484}>
          <mesh name="Text" geometry={nodes.Text.geometry} material={materials['Blue Car Paint']} />
          <mesh name="Text_1" geometry={nodes.Text_1.geometry} material={materials['Gray Car Paint']} />
        </group>
      </group>
    </group>
  )
}


